version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Use Development for easier debugging
      - ConnectionStrings__DefaultConnection=Data Source=/data/db.sqlite  # Set the connection string
    volumes:
      - ./Infrastructure/Data:/data  # Mount the local folder to /data in the container

# Define volumes if you need to persist SQLite data separately
volumes:
  sqlite_data:
    driver: local  # This is optional for SQLite, as the volume is handled in the service definition
