version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Use Development for easier debugging
      - ConnectionStrings__DefaultConnection=Data Source=/data/db.sqlite  # Use volume path
    volumes:
      - ./Infrastructure/Data:/data  # Mount the local folder to /data in the container

# Removed db service since SQLite is managed by the webapi service

volumes:
  sqlite_data:
    driver: local  # Not needed if not used
