# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BitCubeDevDockerApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bitcubecontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a9ca4cea3ecd4299a6b75cfbfbbfc4bb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2ab139deab1a445488fafbf037105f9e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bitcubecontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9ca4cea3ecd4299a6b75cfbfbbfc4bb }}/:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BitCubeDevDockerApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f509ef7b08104b73b65ed869f9170608 }}
        images: 'bitcubecontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9ca4cea3ecd4299a6b75cfbfbbfc4bb }}/:${{ github.sha }}'